### ISSUE TITLE
Estudiar un remplazo de bootstrap

### ISSUE THREAD

**Issue by cmaureir** [python-discord-es/web#3]
Para la primera versión del sitio web se está utilizando bootstrap, que si bien es bastante conveniente, hace que la carga del sitio sea un poco más lenta sobre todo considerando que es solo un sitio estático.

El CSS que utilizamos actualmente pesa 212K, y además tenemos la dependencia del archivo `js` de bootstrap.

Existen muchos frameworks minimalistas que valdría la pena analizar para poder utilizar en vez de bootstrap y conseguir un look-and-feel similar:

* https://picocss.com/
* https://simplecss.org/
* https://milligram.io/
* https://bulma.io/
* https://www.beercss.com/
* https://minicss.org/
* https://picturepan2.github.io/spectre/

**Comment by ErikGIovani** [comment]
Puedo recrear el diseño sin ningun framework de css y hacerlo con sass para poder ir haciendo mejoras graduales y solo tener el css necesario y que tenga un peso mucho menor que el de todos los frameworks

**Comment by cmaureir** [comment]
La idea del framework, es principalmente para invitar a personas a que puedan hacer algún cambio, pues en ese caso pueden visitar el sitio web, y saber como funcionan los distintos elementos gráficos.

El problema que veo con 'cocinar todo en casa' es que estaríamos reinventando la rueda, y la gente tendría más dudas en 'como agregar un botón', 'cómo hacer una sección que use el X% de una columna' y cosas así...por eso nos quitamos ese problema de encima de 'crear un framework y documentarlo' para que la gente lo use, con solo usar un framework ya existente.

Igual de momento, tómate este issue como de baja prioridad, creo que mejorar el contenido actual del sitio es mucho más importante para que la gente pueda visitarlo más a menudo!

**Comment by ErikGIovani** [comment]
OK

**Comment by cmaureir** [comment]
La nueva versión del sitio usa [Cirrus UI](https://www.cirrus-ui.com/)
